// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: network.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Network_CreateGraph_FullMethodName     = "/netproto.Network/CreateGraph"
	Network_DeleteGraph_FullMethodName     = "/netproto.Network/DeleteGraph"
	Network_ShowGraph_FullMethodName       = "/netproto.Network/ShowGraph"
	Network_RequestSolution_FullMethodName = "/netproto.Network/RequestSolution"
	Network_SetCBSLocation_FullMethodName  = "/netproto.Network/SetCBSLocation"
)

// NetworkClient is the client API for Network service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkClient interface {
	CreateGraph(ctx context.Context, in *CreateGraphRequest, opts ...grpc.CallOption) (*CreateGraphResponse, error)
	DeleteGraph(ctx context.Context, in *DeleteGraphRequest, opts ...grpc.CallOption) (*DeleteGraphResponse, error)
	ShowGraph(ctx context.Context, in *ShowGraphRequest, opts ...grpc.CallOption) (*ShowGraphResponse, error)
	RequestSolution(ctx context.Context, in *SolveRequest, opts ...grpc.CallOption) (*SolveResponse, error)
	SetCBSLocation(ctx context.Context, in *SetCBSRequest, opts ...grpc.CallOption) (*SetCBSResponse, error)
}

type networkClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkClient(cc grpc.ClientConnInterface) NetworkClient {
	return &networkClient{cc}
}

func (c *networkClient) CreateGraph(ctx context.Context, in *CreateGraphRequest, opts ...grpc.CallOption) (*CreateGraphResponse, error) {
	out := new(CreateGraphResponse)
	err := c.cc.Invoke(ctx, Network_CreateGraph_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) DeleteGraph(ctx context.Context, in *DeleteGraphRequest, opts ...grpc.CallOption) (*DeleteGraphResponse, error) {
	out := new(DeleteGraphResponse)
	err := c.cc.Invoke(ctx, Network_DeleteGraph_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) ShowGraph(ctx context.Context, in *ShowGraphRequest, opts ...grpc.CallOption) (*ShowGraphResponse, error) {
	out := new(ShowGraphResponse)
	err := c.cc.Invoke(ctx, Network_ShowGraph_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) RequestSolution(ctx context.Context, in *SolveRequest, opts ...grpc.CallOption) (*SolveResponse, error) {
	out := new(SolveResponse)
	err := c.cc.Invoke(ctx, Network_RequestSolution_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClient) SetCBSLocation(ctx context.Context, in *SetCBSRequest, opts ...grpc.CallOption) (*SetCBSResponse, error) {
	out := new(SetCBSResponse)
	err := c.cc.Invoke(ctx, Network_SetCBSLocation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkServer is the server API for Network service.
// All implementations must embed UnimplementedNetworkServer
// for forward compatibility
type NetworkServer interface {
	CreateGraph(context.Context, *CreateGraphRequest) (*CreateGraphResponse, error)
	DeleteGraph(context.Context, *DeleteGraphRequest) (*DeleteGraphResponse, error)
	ShowGraph(context.Context, *ShowGraphRequest) (*ShowGraphResponse, error)
	RequestSolution(context.Context, *SolveRequest) (*SolveResponse, error)
	SetCBSLocation(context.Context, *SetCBSRequest) (*SetCBSResponse, error)
	mustEmbedUnimplementedNetworkServer()
}

// UnimplementedNetworkServer must be embedded to have forward compatible implementations.
type UnimplementedNetworkServer struct {
}

func (UnimplementedNetworkServer) CreateGraph(context.Context, *CreateGraphRequest) (*CreateGraphResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGraph not implemented")
}
func (UnimplementedNetworkServer) DeleteGraph(context.Context, *DeleteGraphRequest) (*DeleteGraphResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGraph not implemented")
}
func (UnimplementedNetworkServer) ShowGraph(context.Context, *ShowGraphRequest) (*ShowGraphResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowGraph not implemented")
}
func (UnimplementedNetworkServer) RequestSolution(context.Context, *SolveRequest) (*SolveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestSolution not implemented")
}
func (UnimplementedNetworkServer) SetCBSLocation(context.Context, *SetCBSRequest) (*SetCBSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCBSLocation not implemented")
}
func (UnimplementedNetworkServer) mustEmbedUnimplementedNetworkServer() {}

// UnsafeNetworkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkServer will
// result in compilation errors.
type UnsafeNetworkServer interface {
	mustEmbedUnimplementedNetworkServer()
}

func RegisterNetworkServer(s grpc.ServiceRegistrar, srv NetworkServer) {
	s.RegisterService(&Network_ServiceDesc, srv)
}

func _Network_CreateGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).CreateGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Network_CreateGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).CreateGraph(ctx, req.(*CreateGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_DeleteGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).DeleteGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Network_DeleteGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).DeleteGraph(ctx, req.(*DeleteGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_ShowGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).ShowGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Network_ShowGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).ShowGraph(ctx, req.(*ShowGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_RequestSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).RequestSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Network_RequestSolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).RequestSolution(ctx, req.(*SolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Network_SetCBSLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCBSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServer).SetCBSLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Network_SetCBSLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServer).SetCBSLocation(ctx, req.(*SetCBSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Network_ServiceDesc is the grpc.ServiceDesc for Network service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Network_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netproto.Network",
	HandlerType: (*NetworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGraph",
			Handler:    _Network_CreateGraph_Handler,
		},
		{
			MethodName: "DeleteGraph",
			Handler:    _Network_DeleteGraph_Handler,
		},
		{
			MethodName: "ShowGraph",
			Handler:    _Network_ShowGraph_Handler,
		},
		{
			MethodName: "RequestSolution",
			Handler:    _Network_RequestSolution_Handler,
		},
		{
			MethodName: "SetCBSLocation",
			Handler:    _Network_SetCBSLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "network.proto",
}
