apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  annotations:
    k8s.v1.cni.cncf.io/networks: xp-net
spec:
  replicas: {{.Values.Replicas }}
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - name: inventory-api
        image: {{.Values.orchestrator.inventory.api.image | quote}}
        ports:
          - containerPort: {{.Values.orchestrator.inventory.api.port }}
        env:
          - name: ETCDHOST
            value: {{.Values.etcd.host | quote}}
          - name: ETCDPORT
            value: {{.Values.etcd.port | quote}}
          - name: INVENTORYPORT
            value: {{.Values.orchestrator.inventory.api.port | quote}}
          - name: DEBUG
            value: {{.Values.orchestrator.inventory.api.debug | quote}}
        volumeMounts:
        - name: {{ .Release.Name }}-vol
          mountPath: /var/orchestrator/config.cfg
          subPath: config.cfg
          readOnly: true
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
      - name: etcd
        image: {{.Values.etcd.image | quote}}
        ports:
          - containerPort: {{.Values.etcd.port }}
        env:
          - name: ALLOW_NONE_AUTHENTICATION
            value: "yes"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
      - name: discovery-api
        image: {{.Values.orchestrator.discovery.api.image | quote}}
        ports:
          - containerPort: {{.Values.orchestrator.discovery.api.port }}
        env:
          - name: ETCDHOST
            value: {{.Values.etcd.host| quote}}
          - name: ETCDPORT
            value: {{.Values.etcd.port | quote}}
          - name: DISCOVERYPORT
            value: {{.Values.orchestrator.discovery.api.port | quote}}
          - name: DEBUG
            value: {{.Values.orchestrator.discovery.api.debug | quote}}
        volumeMounts:
        - name: {{ .Release.Name }}-vol
          mountPath: /var/orchestrator/config.cfg
          subPath: config.cfg
          readOnly: true
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
      - name: discovery-scanner
        image: {{.Values.orchestrator.discovery.scanner.image | quote}}
        ports:
          - containerPort: {{.Values.orchestrator.discovery.scanner.port }}
        env:
          - name: ETCDHOST
            value: {{.Values.etcd.host | quote}}
          - name: ETCDPORT
            value: {{.Values.etcd.port | quote}}
          - name: DISCOVERYPORT
            value: {{.Values.orchestrator.discovery.scanner.port | quote}}
          - name: DEBUG
            value: {{.Values.orchestrator.discovery.scanner.debug | quote}}
        volumeMounts:
        - name: {{ .Release.Name }}-vol
          mountPath: /var/orchestrator/config.cfg
          subPath: config.cfg
          readOnly: true
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
      - name: mock-discovery
        image: {{.Values.orchestrator.mock.discovery.image | quote}}
        ports:
          - containerPort: {{.Values.orchestrator.mock.discovery.port }}
        env:
          - name: ETCDHOST
            value: {{.Values.etcd.host | quote}}
          - name: ETCDPORT
            value: {{.Values.etcd.port | quote}}
          - name: MOCKDISCOVERYPORT
            value: {{.Values.orchestrator.mock.discovery.port | quote}}
          - name: DEBUG
            value: {{.Values.orchestrator.mock.discovery.debug | quote}}
        volumeMounts:
        - name: {{ .Release.Name }}-vol
          mountPath: /var/orchestrator/config.cfg
          subPath: config.cfg
          readOnly: true
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
      - name: network
        image: {{.Values.orchestrator.sabres.network.image | quote}}
        ports:
          - containerPort: {{.Values.orchestrator.sabres.network.port }}
        env:
          - name: INVENTORYHOST
            value: {{.Values.orchestrator.inventory.api.host | quote}}
          - name: INVENTORYPORT 
            value: {{.Values.orchestrator.inventory.api.port | quote}}
          - name: DEBUG
            value: {{.Values.orchestrator.sabres.network.debug | quote}}
        volumeMounts:
        - name: {{ .Release.Name }}-vol
          mountPath: /var/orchestrator/config.cfg
          subPath: config.cfg
          readOnly: true
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
      - name: cbs
        image: {{.Values.orchestrator.sabres.cbs.image | quote}}
        ports:
          - containerPort: {{.Values.orchestrator.sabres.cbs.port }}
        env:
          - name: DEBUG
            value: {{.Values.orchestrator.sabres.cbs.debug | quote}}
        volumeMounts:
        - name: {{ .Release.Name }}-vol
          mountPath: /var/orchestrator/config.cfg
          subPath: config.cfg
          readOnly: true
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
      - name: manager
        image: {{.Values.orchestrator.sabres.manager.image | quote}}
        ports:
          - containerPort: {{.Values.orchestrator.sabres.manager.port }}
        env:
          - name: ETCDHOST
            value: {{.Values.etcd.host | quote}}
          - name: ETCDPORT
            value: {{.Values.etcd.port | quote}}
          - name: INVENTORYHOST
            value: {{.Values.orchestrator.inventory.api.host | quote}}
          - name: INVENTORYPORT 
            value: {{.Values.orchestrator.inventory.api.port | quote}}
          - name: NETWORKHOST
            value: {{.Values.orchestrator.network.api.host | quote}}
          - name: NETWORKPORT 
            value: {{.Values.orchestrator.network.api.port | quote}}
          - name: CBSHOST
            value: {{.Values.orchestrator.cbs.api.host | quote}}
          - name: CBSPORT 
            value: {{.Values.orchestrator.cbs.api.port | quote}}
          - name: DEBUG
            value: {{.Values.orchestrator.sabres.manager.debug | quote}}
        volumeMounts:
        - name: {{ .Release.Name }}-vol
          mountPath: /var/orchestrator/config.cfg
          subPath: config.cfg
          readOnly: true
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
        - name: {{ .Release.Name }}-vol
          configMap:
            name: {{ .Release.Name }}-configmap

